In [1]:
import os
import numpy as np
import pandas as pd
from scipy import interpolate
from scipy.signal import resample
import json
import warnings
from collections import defaultdict
warnings.filterwarnings("ignore")

In [2]:
import mne
from mne.preprocessing import ICA
try:
    from mne_icalabel import label_components
except Exception:
    label_components = None

In [3]:
# multi-scale sampling rates
SAMPLE_RATE_LIST = [200, 100, 50]  # Hz

# fixed segment length in samples (timestamps)
SEG_LEN = 400  # number of time steps per segment
# overlap in samples (timestamps), not in seconds
OVERLAP = 200    # e.g. 200 means 50% overlap for SEG_LEN=400

assert 0 <= OVERLAP < SEG_LEN, "OVERLAP must be in [0, SEG_LEN)."

sub_folder_path = f"L{SEG_LEN}"
sub_folder_path

'L400'

In [4]:
# root dir
root = 'TDBRAIN\derivatives'
# participants file path
ptc_path = os.path.join(root, 'TDBRAIN_participants_V2.tsv')
ptc = pd.read_csv(ptc_path, sep='\t')
ptc

,participants_ID,DISC/REP,indication,formal_status,Dataset,Consent,sessSeason,sessTime,Responder,Remitter,...,BDI_post,rTMS PROTOCOL,ADHD_pre_Hyp_leading,ADHD_pre_Att_leading,ADHD_post_Att_leading,ADHD_post_Hyp_leading,NF Protocol,YBOCS_pre,YBOCS_post,Unnamed: 110
0,sub-19681349,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,2,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
1,sub-19681385,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
2,sub-19684666,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
3,sub-19686324,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,2,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
4,sub-19687321,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,3,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,sub-88078837,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1346,sub-88079017,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Labels

In [5]:
# delete invalid participants and the participants with NAN participants_ID
ptc = ptc[~(ptc['participants_ID'].isna())]
ptc

,participants_ID,DISC/REP,indication,formal_status,Dataset,Consent,sessSeason,sessTime,Responder,Remitter,...,BDI_post,rTMS PROTOCOL,ADHD_pre_Hyp_leading,ADHD_pre_Att_leading,ADHD_post_Att_leading,ADHD_post_Hyp_leading,NF Protocol,YBOCS_pre,YBOCS_post,Unnamed: 110
0,sub-19681349,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,2,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
1,sub-19681385,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
2,sub-19684666,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
3,sub-19686324,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,2,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
4,sub-19687321,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,3,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1342,sub-88078657,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,fall,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1343,sub-88078749,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1344,sub-88078793,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1345,sub-88078837,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1346,sub-88079017,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Get duplicate values of participants_id
l = ptc.drop_duplicates(['participants_ID'],keep=False)['participants_ID'].to_list()
dup_ptc = ptc[~(ptc['participants_ID'].isin(l))]
dup_ptc

,participants_ID,DISC/REP,indication,formal_status,Dataset,Consent,sessSeason,sessTime,Responder,Remitter,...,BDI_post,rTMS PROTOCOL,ADHD_pre_Hyp_leading,ADHD_pre_Att_leading,ADHD_post_Att_leading,ADHD_post_Hyp_leading,NF Protocol,YBOCS_pre,YBOCS_post,Unnamed: 110
4,sub-19687321,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,3,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
5,sub-19687321,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,3,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
7,sub-19690494,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
8,sub-19690494,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
9,sub-19690969,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958,sub-88047289,DISCOVERY,DEPERSONALIZATION,UNKNOWN,NaN,YES,summer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
962,sub-88047649,DISCOVERY,OCD,OCD,OCD,YES,summer,NaN,1,1,...,6,7,NaN,NaN,NaN,NaN,NaN,23,12,NaN
963,sub-88047649,DISCOVERY,OCD,OCD,OCD,YES,summer,NaN,1,1,...,6,7,NaN,NaN,NaN,NaN,NaN,23,12,NaN
972,sub-88048193,DISCOVERY,OCD,OCD,OCD,YES,summer,NaN,1,0,...,0,7,NaN,NaN,NaN,NaN,NaN,22,13,NaN
973,sub-88048193,DISCOVERY,OCD,OCD,OCD,YES,winter,NaN,1,0,...,0,7,NaN,NaN,NaN,NaN,NaN,22,13,NaN

In [7]:
# Test if the same participant has different indications for different sessions
for i in range(len(dup_ptc)):
    temp = dup_ptc[dup_ptc['participants_ID']==dup_ptc['participants_ID'].iloc[i]].drop_duplicates(['indication'])
    if len(temp)!=1:
        print(len(temp))
        print('The different sessions in the same participant may have different indications!')

2
The different sessions in the same participant may have different indications!
2
The different sessions in the same participant may have different indications!

In [8]:
# EEG data preprocessing

# all disease mapping
all_dise_dict = {}
ls_ind = list(ptc['indication'].unique())
for i in range(len(ls_ind)):
    all_dise_dict[ls_ind[i]] = i
print(all_dise_dict)
    
ptc['indication_id'] = ptc['indication'].map(all_dise_dict)
ptc

{'REPLICATION': 0, 'BURNOUT': 1, 'SMC': 2, 'HEALTHY': 3, 'Dyslexia': 4, 'CHRONIC PAIN': 5, 'MDD': 6, nan: 7, 'ADHD': 8, 'ADHD/ASPERGER': 9, 'PDD NOS/DYSLEXIA': 10, 'PDD NOS': 11, 'WHIPLASH': 12, 'ANXIETY': 13, 'ADHD/DYSLEXIA': 14, 'ASD': 15, 'TINNITUS': 16, 'OCD': 17, 'Tinnitus': 18, 'PDD NOS ': 19, 'PANIC': 20, 'MDD/ANXIETY': 21, 'MIGRAINE': 22, 'PDD NOS/ANXIETY': 23, 'PARKINSON': 24, 'BIPOLAR': 25, 'MDD/bipolar': 26, 'DYSPRAXIA': 27, 'TINNITUS/MDD': 28, 'ADHD/ASD/ANXIETY': 29, 'MDD/ADHD': 30, 'ADHD/PDD NOS': 31, 'MDD/BIPOLAR': 32, 'ASPERGER': 33, 'ADHD/EPILEPSY': 34, 'MDD/PAIN': 35, 'PDD NOS/GTS': 36, 'PDD NOS/ADHD': 37, 'PDD NOS/ASD': 38, 'TBI': 39, 'ADHD/ANXIETY': 40, 'ADHD/DYSLEXIA/DYSCALCULIA': 41, 'ADHD/MDD': 42, 'MDD/PANIC': 43, 'DEPERSONALIZATION': 44, 'MDD/TRAUMA': 45, 'PTSD/ADHD': 46, 'OCD/DPS': 47, 'MDD/OCD': 48, 'MDD/TUMOR': 49, 'ADHD/GTS': 50, 'OCD/MDD': 51, 'CONVERSION DX': 52, 'ASD/ASPERGER': 53, 'MDD/ADHD/LYME': 54, 'ADHD/OCD': 55, 'MSA-C': 56, 'OCD/ASD': 57, 'STROKE/PAIN': 58, 'STROKE ': 59, 'MDD/OCD/ADHD': 60, 'EPILEPSY/OCD': 61, 'ADHD ': 62, 'INSOMNIA': 63, 'MDD/ADHD/ANOREXIA': 64, 'MDD/ANXIETY/TINNITUS': 65}

,participants_ID,DISC/REP,indication,formal_status,Dataset,Consent,sessSeason,sessTime,Responder,Remitter,...,rTMS PROTOCOL,ADHD_pre_Hyp_leading,ADHD_pre_Att_leading,ADHD_post_Att_leading,ADHD_post_Hyp_leading,NF Protocol,YBOCS_pre,YBOCS_post,Unnamed: 110,indication_id
0,sub-19681349,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,2,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
1,sub-19681385,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
2,sub-19684666,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
3,sub-19686324,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,2,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
4,sub-19687321,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,3,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1342,sub-88078657,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,fall,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1343,sub-88078749,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1344,sub-88078793,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1345,sub-88078837,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1346,sub-88079017,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63

In [9]:
# EEG data preprocessing

# all disease mapping
all_dise_dict = {}
ls_ind = list(ptc['indication'].unique())
for i in range(len(ls_ind)):
    all_dise_dict[ls_ind[i]] = i
print(all_dise_dict)
    
ptc['indication_id'] = ptc['indication'].map(all_dise_dict)
ptc

{'REPLICATION': 0, 'BURNOUT': 1, 'SMC': 2, 'HEALTHY': 3, 'Dyslexia': 4, 'CHRONIC PAIN': 5, 'MDD': 6, nan: 7, 'ADHD': 8, 'ADHD/ASPERGER': 9, 'PDD NOS/DYSLEXIA': 10, 'PDD NOS': 11, 'WHIPLASH': 12, 'ANXIETY': 13, 'ADHD/DYSLEXIA': 14, 'ASD': 15, 'TINNITUS': 16, 'OCD': 17, 'Tinnitus': 18, 'PDD NOS ': 19, 'PANIC': 20, 'MDD/ANXIETY': 21, 'MIGRAINE': 22, 'PDD NOS/ANXIETY': 23, 'PARKINSON': 24, 'BIPOLAR': 25, 'MDD/bipolar': 26, 'DYSPRAXIA': 27, 'TINNITUS/MDD': 28, 'ADHD/ASD/ANXIETY': 29, 'MDD/ADHD': 30, 'ADHD/PDD NOS': 31, 'MDD/BIPOLAR': 32, 'ASPERGER': 33, 'ADHD/EPILEPSY': 34, 'MDD/PAIN': 35, 'PDD NOS/GTS': 36, 'PDD NOS/ADHD': 37, 'PDD NOS/ASD': 38, 'TBI': 39, 'ADHD/ANXIETY': 40, 'ADHD/DYSLEXIA/DYSCALCULIA': 41, 'ADHD/MDD': 42, 'MDD/PANIC': 43, 'DEPERSONALIZATION': 44, 'MDD/TRAUMA': 45, 'PTSD/ADHD': 46, 'OCD/DPS': 47, 'MDD/OCD': 48, 'MDD/TUMOR': 49, 'ADHD/GTS': 50, 'OCD/MDD': 51, 'CONVERSION DX': 52, 'ASD/ASPERGER': 53, 'MDD/ADHD/LYME': 54, 'ADHD/OCD': 55, 'MSA-C': 56, 'OCD/ASD': 57, 'STROKE/PAIN': 58, 'STROKE ': 59, 'MDD/OCD/ADHD': 60, 'EPILEPSY/OCD': 61, 'ADHD ': 62, 'INSOMNIA': 63, 'MDD/ADHD/ANOREXIA': 64, 'MDD/ANXIETY/TINNITUS': 65}

,participants_ID,DISC/REP,indication,formal_status,Dataset,Consent,sessSeason,sessTime,Responder,Remitter,...,rTMS PROTOCOL,ADHD_pre_Hyp_leading,ADHD_pre_Att_leading,ADHD_post_Att_leading,ADHD_post_Hyp_leading,NF Protocol,YBOCS_pre,YBOCS_post,Unnamed: 110,indication_id
0,sub-19681349,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,2,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
1,sub-19681385,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
2,sub-19684666,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
3,sub-19686324,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,2,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
4,sub-19687321,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,3,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1342,sub-88078657,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,fall,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1343,sub-88078749,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1344,sub-88078793,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1345,sub-88078837,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1346,sub-88079017,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63

In [10]:
# Drop duplicate participants
ptc = ptc.drop_duplicates(['participants_ID'])
ptc

,participants_ID,DISC/REP,indication,formal_status,Dataset,Consent,sessSeason,sessTime,Responder,Remitter,...,rTMS PROTOCOL,ADHD_pre_Hyp_leading,ADHD_pre_Att_leading,ADHD_post_Att_leading,ADHD_post_Hyp_leading,NF Protocol,YBOCS_pre,YBOCS_post,Unnamed: 110,indication_id
0,sub-19681349,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,2,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
1,sub-19681385,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
2,sub-19684666,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,1,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
3,sub-19686324,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,2,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
4,sub-19687321,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,3,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1342,sub-88078657,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,fall,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1343,sub-88078749,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1344,sub-88078793,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1345,sub-88078837,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63
1346,sub-88079017,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63

In [11]:
# label.npy
# initialization column 'subject_id'
ptc['subject_id'] = np.arange(1, ptc.shape[0] + 1)
ptc

,participants_ID,DISC/REP,indication,formal_status,Dataset,Consent,sessSeason,sessTime,Responder,Remitter,...,ADHD_pre_Hyp_leading,ADHD_pre_Att_leading,ADHD_post_Att_leading,ADHD_post_Hyp_leading,NF Protocol,YBOCS_pre,YBOCS_post,Unnamed: 110,indication_id,subject_id
0,sub-19681349,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0,1
1,sub-19681385,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0,2
2,sub-19684666,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0,3
3,sub-19686324,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0,4
4,sub-19687321,REPLICATION,REPLICATION,REPLICATION,REPLICATION,YES,REPLICATION,REPLICATION,REPLICATION,REPLICATION,...,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,REPLICATION,NaN,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1342,sub-88078657,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,fall,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63,1269
1343,sub-88078749,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63,1270
1344,sub-88078793,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63,1271
1345,sub-88078837,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63,1272
1346,sub-88079017,DISCOVERY,INSOMNIA,INSOMNIA,NaN,YES,winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63,1273

In [12]:
# build subject info: "sub-XXX" -> (label, pid)
sub_info = {}  # key: subject name, value: (label, pid)
for row in ptc.itertuples(index=False):
    sub_name = row[-1]          
    pid = int(sub_name)   # convert '001' -> 1
    label = row[-2]   
    sub_info[sub_name] = (label, pid)

len(sub_info), list(sub_info.items())[:5]

(1273, [(1, (0, 1)), (2, (0, 2)), (3, (0, 3)), (4, (0, 4)), (5, (0, 5))])

## Features

In [13]:
def data_preprocessing(
    eeg_data: np.ndarray,
    ch_names: list,
    source_sample_rate: int,
    notch_freq: float = 60.0,
    l_freq: float = 0.5,
    h_freq: float = 45.0,
    verbose=True
):
    """
    Clean EEG data using bandpass filtering, percentile-based bad channel detection,
    ICA + ICLabel artifact removal, resampling, re-referencing, epoching, and z-score normalization.

    Args:
        eeg_data (np.ndarray): EEG data, shape (T, C).
        ch_names (list): List of channel names.
        source_sample_rate (int): Original sampling frequency of the EEG data.
        notch_freq (float): Notch filter frequency (default: 60 Hz).
        l_freq (float): Low cutoff frequency for bandpass filter (default: 0.5 Hz).
        h_freq (float): High cutoff frequency for bandpass filter (default: 40 Hz).
        verbose (bool): Verbose output.

    Returns:
        mne.io.Raw: Preprocessed MNE Raw object.
    """
    # 1. Construct MNE Raw object
    info = mne.create_info(ch_names=ch_names, sfreq=source_sample_rate, ch_types=['eeg'] * len(ch_names))
    raw = mne.io.RawArray(eeg_data.T, info)

    # 2. Set Montage
    raw.set_montage(mne.channels.make_standard_montage('standard_1020'))
    if verbose:
        print("✔ Montage set: 'standard_1020'.")
        
    # 3. Notch Filter at 50 Hz
    raw.notch_filter(freqs=notch_freq, picks="eeg", verbose=False)
    if verbose:
        print(f"✔ Notch @ {notch_freq} Hz")

    #  Bandpass Filter (0.5–45 Hz)
    raw.filter(l_freq=l_freq, h_freq=h_freq, verbose=False)
    if verbose:
        print(f"✔ Bandpass filter applied ({l_freq}–{h_freq} Hz).")
        
    # 5. ICA + ICLabel
    raw_ica = raw.copy()
    ica = ICA(n_components=None, random_state=97, max_iter='auto')
    ica.fit(raw_ica)
    if verbose:
        print("✔ ICA fitted.")

    try:
        ic_labels = label_components(raw_ica, ica, method='iclabel')
        labels = ic_labels['labels']
        probs = ic_labels['y_pred_proba']

        artifact_thresholds = {
            'eye blink': 0.7,
            'muscle artifact': 0.6,
            'heart beat': 0.5,
            'line noise': 0.8,
            'channel noise': 0.9
        }

        to_exclude = [
            i for i, label in enumerate(labels)
            if label in artifact_thresholds and probs[i] >= artifact_thresholds[label]
        ]
        if to_exclude:
            ica.exclude = to_exclude
            ica.apply(raw)
            if verbose:
                print(f"✔ ICA applied. Excluded components: {to_exclude}")
        else:
            if verbose:
                print("No ICs exceeded artifact thresholds. No components excluded.")

    except Exception as e:
        if verbose:
            print(f"⚠ ICLabel failed: {e}. Proceeding without ICA-based removal.")
        
    return raw

In [14]:
def resample_time_series(data, original_fs, target_fs):
    """
    Resample each channel independently.
    data: (T_raw, C)
    return: (T_new, C)
    """
    T, C = data.shape
    new_length = int(T * target_fs / original_fs)
    resampled_data = np.zeros((new_length, C), dtype=np.float32)
    for i in range(C):
        # resample one channel
        resampled_data[:, i] = resample(data[:, i], new_length)
    return resampled_data


def compute_step(seg_len, overlap):
    """
    Compute sliding step (in samples) given segment length and overlap.
    """
    step = seg_len - overlap
    if step <= 0:
        raise ValueError(f"Invalid overlap={overlap}: step <= 0.")
    return step


def compute_num_segments(num_samples, seg_len, step):
    """
    Compute how many segments can be extracted from a sequence
    with given segment length and step.
    """
    if num_samples < seg_len:
        return 0
    return 1 + (num_samples - seg_len) // step

## PASS 1: Find total number of segments across all subjects

In [15]:
# Loop through each subject and session to preprocess the EEG data
subject_segment_counts = defaultdict(lambda: defaultdict(int))
N_total = 0
standard_channels = ['Fp1','Fp2','F7','F3','Fz','F4','F8','FC3','FCz','FC4','T7',
                     'C3','Cz','C4','T8','CP3','CPz','CP4','P7','P3','Pz','P4','P8','O1','Oz','O2']
n_channels = len(standard_channels)

# step (timestamps)
STEP = compute_step(SEG_LEN, OVERLAP)
print("SEG_LEN =", SEG_LEN, "OVERLAP =", OVERLAP, "STEP =", STEP, "\n")

sub_id = 1
ORIGINAL_SAMPLE_RATE = 500  # original sampling rate
ls_ptc = ptc['participants_ID'].to_list()
for sub in os.listdir(root):
    # select valid subjects
    if sub in ls_ptc:
        print(sub)
        print("Effective subject number: ", sub_id)
        sub_path = os.path.join(root, sub) 
        for ses in os.listdir(sub_path):
            print(ses)
            print('-----------')
            ses_path = os.path.join(sub_path, ses, 'eeg')
            for task in os.listdir(ses_path):
                if 'EC' in task:
                    print("Eye closed")
                else:
                    print("Eye open")
                task_path = os.path.join(ses_path, task)
                data = pd.read_csv(task_path, usecols=standard_channels).to_numpy()
                print("Raw data shape ", data.shape)
                T_raw = data.shape[0]
                for fs in SAMPLE_RATE_LIST:
                    T_res = int(T_raw * fs / ORIGINAL_SAMPLE_RATE)
                    # compute number of segments
                    n_seg = compute_num_segments(T_res, SEG_LEN, STEP)
                    subject_segment_counts[sub_id][fs] += n_seg
                    N_total += n_seg
                    print(f"fs={fs}Hz: T_res={T_res}, STEP={STEP}, n_seg={n_seg}")
                print('------------End of Task-------------------')
        print("Total segments for Session", sub_id, ":", sum(subject_segment_counts[sub_id][fs] for fs in SAMPLE_RATE_LIST))
        sub_id += 1
        print('--------------------------------------------------------------------------\n')
    else:
        print(" ", sub, " is not in the list of valid subjects.")
        print('--------------------------------------------------------------------------\n')
        continue
        
        
print("\n===================================")
print("Total segments N_total =", N_total)
print("Channels =", n_channels)
print("===================================")

if N_total == 0:
    raise RuntimeError("No segments found. Please check SEG_LEN / OVERLAP.")

SEG_LEN = 400 OVERLAP = 200 STEP = 200

sub-19681349
Effective subject number:  1
ses-1
-----------
Eye closed
Raw data shape  (60003, 26)
fs=200Hz: T_res=24001, STEP=200, n_seg=119
fs=100Hz: T_res=12000, STEP=200, n_seg=59
fs=50Hz: T_res=6000, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60014, 26)
fs=200Hz: T_res=24005, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 1 : 414
--------------------------------------------------------------------------

sub-19681385
Effective subject number:  2
ses-1
-----------
Eye closed
Raw data shape  (60015, 26)
fs=200Hz: T_res=24006, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60020, 26)
fs=200Hz: T_res=24008, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 2 : 414
--------------------------------------------------------------------------

sub-19684666
Effective subject number:  3
ses-1
-----------
Eye closed
Raw data shape  (60003, 26)
fs=200Hz: T_res=24001, STEP=200, n_seg=119
fs=100Hz: T_res=12000, STEP=200, n_seg=59
fs=50Hz: T_res=6000, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60012, 26)
fs=200Hz: T_res=24004, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 3 : 414
--------------------------------------------------------------------------

sub-19686324
Effective subject number:  4
ses-1
-----------
Eye closed
Raw data shape  (60015, 26)
fs=200Hz: T_res=24006, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60009, 26)
fs=200Hz: T_res=24003, STEP=200, n_seg=119
fs=100Hz: T_res=12001, STEP=200, n_seg=59
fs=50Hz: T_res=6000, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 4 : 414
--------------------------------------------------------------------------

sub-19687321
Effective subject number:  5
ses-1
-----------
Eye closed
Raw data shape  (60015, 26)
fs=200Hz: T_res=24006, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60015, 26)
fs=200Hz: T_res=24006, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60003, 26)
fs=200Hz: T_res=24001, STEP=200, n_seg=119
fs=100Hz: T_res=12000, STEP=200, n_seg=59
fs=50Hz: T_res=6000, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60020, 26)
fs=200Hz: T_res=24008, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 5 : 828
--------------------------------------------------------------------------

sub-19687396
Effective subject number:  6
ses-1
-----------
Eye closed
Raw data shape  (60003, 26)
fs=200Hz: T_res=24001, STEP=200, n_seg=119
fs=100Hz: T_res=12000, STEP=200, n_seg=59
fs=50Hz: T_res=6000, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60003, 26)
fs=200Hz: T_res=24001, STEP=200, n_seg=119
fs=100Hz: T_res=12000, STEP=200, n_seg=59
fs=50Hz: T_res=6000, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 6 : 414
--------------------------------------------------------------------------

sub-19690494
Effective subject number:  7
ses-1
-----------
Eye closed
Raw data shape  (60021, 26)
fs=200Hz: T_res=24008, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60015, 26)
fs=200Hz: T_res=24006, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 7 : 828
--------------------------------------------------------------------------

sub-19690969
Effective subject number:  8
ses-1
-----------
Eye closed
Raw data shape  (60008, 26)
fs=200Hz: T_res=24003, STEP=200, n_seg=119
fs=100Hz: T_res=12001, STEP=200, n_seg=59
fs=50Hz: T_res=6000, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (59960, 26)
fs=200Hz: T_res=23984, STEP=200, n_seg=118
fs=100Hz: T_res=11992, STEP=200, n_seg=58
fs=50Hz: T_res=5996, STEP=200, n_seg=28
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 8 : 825
--------------------------------------------------------------------------

sub-19691048
Effective subject number:  9
ses-1
-----------
Eye closed
Raw data shape  (60015, 26)
fs=200Hz: T_res=24006, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60003, 26)
fs=200Hz: T_res=24001, STEP=200, n_seg=119
fs=100Hz: T_res=12000, STEP=200, n_seg=59
fs=50Hz: T_res=6000, STEP=200, n_seg=29
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 9 : 828
--------------------------------------------------------------------------

sub-19691782
Effective subject number:  10
ses-1
-----------
Eye closed
Raw data shape  (59984, 26)
fs=200Hz: T_res=23993, STEP=200, n_seg=118
fs=100Hz: T_res=11996, STEP=200, n_seg=58
fs=50Hz: T_res=5998, STEP=200, n_seg=28
------------End of Task-------------------
Eye open
Raw data shape  (60021, 26)
fs=200Hz: T_res=24008, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 10 : 411
--------------------------------------------------------------------------

sub-19693739
Effective subject number:  11
ses-1
-----------
Eye closed
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 11 : 414
--------------------------------------------------------------------------

sub-19694366
Effective subject number:  12
ses-1
-----------
Eye closed
Raw data shape  (60026, 26)
fs=200Hz: T_res=24010, STEP=200, n_seg=119
fs=100Hz: T_res=12005, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 12 : 414
--------------------------------------------------------------------------

sub-19694625
Effective subject number:  13
ses-1
-----------
Eye closed
Raw data shape  (60029, 26)
fs=200Hz: T_res=24011, STEP=200, n_seg=119
fs=100Hz: T_res=12005, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60014, 26)
fs=200Hz: T_res=24005, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 13 : 828
--------------------------------------------------------------------------

sub-19695359
Effective subject number:  14
ses-1
-----------
Eye closed
Raw data shape  (60026, 26)
fs=200Hz: T_res=24010, STEP=200, n_seg=119
fs=100Hz: T_res=12005, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 14 : 414
--------------------------------------------------------------------------

sub-19696546
Effective subject number:  15
ses-1
-----------
Eye closed
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 15 : 414
--------------------------------------------------------------------------

sub-19696870
Effective subject number:  16
ses-1
-----------
Eye closed
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60026, 26)
fs=200Hz: T_res=24010, STEP=200, n_seg=119
fs=100Hz: T_res=12005, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60012, 26)
fs=200Hz: T_res=24004, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 16 : 828
--------------------------------------------------------------------------

sub-19696913
Effective subject number:  17
ses-1
-----------
Eye closed
Raw data shape  (60021, 26)
fs=200Hz: T_res=24008, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60015, 26)
fs=200Hz: T_res=24006, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 17 : 414
--------------------------------------------------------------------------

sub-19697464
Effective subject number:  18
ses-1
-----------
Eye closed
Raw data shape  (60024, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 18 : 828
--------------------------------------------------------------------------

sub-19698310
Effective subject number:  19
ses-1
-----------
Eye closed
Raw data shape  (60020, 26)
fs=200Hz: T_res=24008, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60020, 26)
fs=200Hz: T_res=24008, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 19 : 414
--------------------------------------------------------------------------

sub-19698421
Effective subject number:  20
ses-1
-----------
Eye closed
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60023, 26)
fs=200Hz: T_res=24009, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 20 : 414
--------------------------------------------------------------------------

sub-19698457
Effective subject number:  21
ses-1
-----------
Eye closed
Raw data shape  (60014, 26)
fs=200Hz: T_res=24005, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60014, 26)
fs=200Hz: T_res=24005, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 21 : 414
--------------------------------------------------------------------------

sub-19699415
Effective subject number:  22
ses-1
-----------
Eye closed
Raw data shape  (60014, 26)
fs=200Hz: T_res=24005, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60014, 26)
fs=200Hz: T_res=24005, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 22 : 414
--------------------------------------------------------------------------

sub-19699864
Effective subject number:  23
ses-1
-----------
Eye closed
Raw data shape  (60014, 26)
fs=200Hz: T_res=24005, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60014, 26)
fs=200Hz: T_res=24005, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60020, 26)
fs=200Hz: T_res=24008, STEP=200, n_seg=119
fs=100Hz: T_res=12004, STEP=200, n_seg=59
fs=50Hz: T_res=6002, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60015, 26)
fs=200Hz: T_res=24006, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 23 : 828
--------------------------------------------------------------------------

sub-19700339
Effective subject number:  24
ses-1
-----------
Eye closed
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60014, 26)
fs=200Hz: T_res=24005, STEP=200, n_seg=119
fs=100Hz: T_res=12002, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 24 : 414
--------------------------------------------------------------------------

sub-19700415
Effective subject number:  25
ses-1
-----------
Eye closed
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 25 : 414
--------------------------------------------------------------------------

sub-19701041
Effective subject number:  26
ses-1
-----------
Eye closed
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 26 : 828
--------------------------------------------------------------------------

sub-19701225
Effective subject number:  27
ses-1
-----------
Eye closed
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Total segments for Session 27 : 414
--------------------------------------------------------------------------

sub-19703032
Effective subject number:  28
ses-1
-----------
Eye closed
Raw data shape  (60018, 26)
fs=200Hz: T_res=24007, STEP=200, n_seg=119
fs=100Hz: T_res=12003, STEP=200, n_seg=59
fs=50Hz: T_res=6001, STEP=200, n_seg=29
------------End of Task-------------------
Eye open
Raw data shape  (60014, 26)

In [16]:
output_root = os.path.join('Processed', sub_folder_path, 'TDBrain')
os.makedirs(output_root, exist_ok=True)

X_path = os.path.join(output_root, 'X.dat')
y_path = os.path.join(output_root, 'y.dat')
meta_path = os.path.join(output_root, 'meta.json')

print("X path:", X_path)
print("y path:", y_path)

# create memmap storage
X_mm = np.memmap(X_path, dtype='float32', mode='w+', shape=(N_total, SEG_LEN, n_channels))
y_mm = np.memmap(y_path, dtype='float32', mode='w+', shape=(N_total, 3))
print("Created memmap for X with shape:", X_mm.shape)

X path: Processed\L400\TDBrain\X.dat
y path: Processed\L400\TDBrain\y.dat
Created memmap for X with shape: (555455, 400, 26)

## PASS 2: Process and store segments into memmap

In [17]:
cur = 0  # current index in memmap
total_seconds_all = 0  # used for total hours calculation

sub_id = 1
ORIGINAL_SAMPLE_RATE = 500  # original sampling rate
ls_ptc = ptc['participants_ID'].to_list()
for sub in os.listdir(root):
    # select valid subjects
    if sub in ls_ptc:
        print(sub)
        print("Effective subject number: ", sub_id)
        sub_label, sub_pid = sub_info[sub_id]
        sub_path = os.path.join(root, sub)
        for ses in os.listdir(sub_path):
            print(ses)
            print('-----------')
            ses_path = os.path.join(sub_path, ses, 'eeg')
            for task in os.listdir(ses_path):
                if 'EC' in task:
                    print("Eye closed")
                else:
                    print("Eye open")
                task_path = os.path.join(ses_path, task)
                data = pd.read_csv(task_path, usecols=standard_channels).to_numpy()
                print("Raw data shape ", data.shape)
                raw = data_preprocessing(
                    eeg_data=data,
                    ch_names=standard_channels,
                    source_sample_rate=ORIGINAL_SAMPLE_RATE,  # original sampling rate
                    notch_freq=50,
                    l_freq=0.5,
                    h_freq=45.0,
                    verbose=True
                )
                data = raw.get_data().T
                T_raw = data.shape[0]
                total_seconds_all += data.shape[0] / ORIGINAL_SAMPLE_RATE
                for fs in SAMPLE_RATE_LIST:
                    # resample to target fs
                    data_resampled = resample_time_series(data, ORIGINAL_SAMPLE_RATE, fs)
                    T_res, _ = data_resampled.shape
                    print(f"fs={fs}Hz: resampled shape={data_resampled.shape}")
        
                    # overlapped sliding window with fixed STEP (in timestamps)
                    starts = np.arange(0, T_res - SEG_LEN + 1, STEP, dtype=int)
                    print(f"fs={fs}Hz: segments={len(starts)}")
        
                    for s in starts:
                        if cur >= N_total:
                            raise RuntimeError("Exceeded predicted N_total.")
        
                        X_mm[cur] = data_resampled[s:s + SEG_LEN]   # (SEG_LEN, C)
                        y_mm[cur, 0] = float(sub_label)       # label
                        y_mm[cur, 1] = float(sub_id)      # Global trial ID
                        y_mm[cur, 2] = float(fs)          # sample rate (scale)
                        cur += 1
                print('------------End of Task-------------------')
        print("Total segments for Session", sub_id, ":", sum(subject_segment_counts[sub_id][fs] for fs in SAMPLE_RATE_LIST))
        sub_id += 1
        print('--------------------------------------------------------------------------\n')
    else:
        print(" ", sub, " is not in the list of valid subjects.")
        print('--------------------------------------------------------------------------\n')
        continue
        
        
total_hours_all = total_seconds_all / 3600.0
print("DONE: cur =", cur, " expected N_total =", N_total)
print(f"Total hours across all subjects: {total_hours_all:.2f} hours")

# flush
del X_mm
del y_mm

sub-19681349
Effective subject number:  1
ses-1
-----------
Eye closed
Raw data shape  (60003, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60003
    Range : 0 ... 60002 =      0.000 ...   120.004 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 9.8s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 1 ICA component
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [14]
fs=200Hz: resampled shape=(24001, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12000, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6000, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (60014, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60014
    Range : 0 ... 60013 =      0.000 ...   120.026 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 0.7s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 3 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0, 14, 23]
fs=200Hz: resampled shape=(24005, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12002, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6001, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Total segments for Session 1 : 414
--------------------------------------------------------------------------

sub-19681385
Effective subject number:  2
ses-1
-----------
Eye closed
Raw data shape  (60015, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60015
    Range : 0 ... 60014 =      0.000 ...   120.028 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 0.7s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 1 ICA component
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [6]
fs=200Hz: resampled shape=(24006, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12003, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6001, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (60020, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60020
    Range : 0 ... 60019 =      0.000 ...   120.038 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 0.7s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 2 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0, 19]
fs=200Hz: resampled shape=(24008, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12004, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6002, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Total segments for Session 2 : 414
--------------------------------------------------------------------------

sub-19684666
Effective subject number:  3
ses-1
-----------
Eye closed
Raw data shape  (60003, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60003
    Range : 0 ... 60002 =      0.000 ...   120.004 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 1.5s.
✔ ICA fitted.
No ICs exceeded artifact thresholds. No components excluded.
fs=200Hz: resampled shape=(24001, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12000, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6000, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (60012, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60012
    Range : 0 ... 60011 =      0.000 ...   120.022 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 12.8s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 4 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0, 1, 19, 22]
fs=200Hz: resampled shape=(24004, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12002, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6001, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Total segments for Session 3 : 414
--------------------------------------------------------------------------

sub-19686324
Effective subject number:  4
ses-1
-----------
Eye closed
Raw data shape  (60015, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60015
    Range : 0 ... 60014 =      0.000 ...   120.028 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 2.1s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 2 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [1, 3]
fs=200Hz: resampled shape=(24006, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12003, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6001, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (60009, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60009
    Range : 0 ... 60008 =      0.000 ...   120.016 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 0.6s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 2 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0, 10]
fs=200Hz: resampled shape=(24003, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12001, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6000, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Total segments for Session 4 : 414
--------------------------------------------------------------------------

sub-19687321
Effective subject number:  5
ses-1
-----------
Eye closed
Raw data shape  (60015, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60015
    Range : 0 ... 60014 =      0.000 ...   120.028 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 12.3s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 1 ICA component
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0]
fs=200Hz: resampled shape=(24006, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12003, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6001, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (60015, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60015
    Range : 0 ... 60014 =      0.000 ...   120.028 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 1.5s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 3 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0, 3, 18]
fs=200Hz: resampled shape=(24006, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12003, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6001, 26)
fs=50Hz: segments=29
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60003, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60003
    Range : 0 ... 60002 =      0.000 ...   120.004 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 3.4s.
✔ ICA fitted.
No ICs exceeded artifact thresholds. No components excluded.
fs=200Hz: resampled shape=(24001, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12000, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6000, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (60020, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60020
    Range : 0 ... 60019 =      0.000 ...   120.038 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 0.5s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 2 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0, 1]
fs=200Hz: resampled shape=(24008, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12004, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6002, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Total segments for Session 5 : 828
--------------------------------------------------------------------------

sub-19687396
Effective subject number:  6
ses-1
-----------
Eye closed
Raw data shape  (60003, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60003
    Range : 0 ... 60002 =      0.000 ...   120.004 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 0.5s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 1 ICA component
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [16]
fs=200Hz: resampled shape=(24001, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12000, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6000, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (60003, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60003
    Range : 0 ... 60002 =      0.000 ...   120.004 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 7.7s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 1 ICA component
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0]
fs=200Hz: resampled shape=(24001, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12000, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6000, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Total segments for Session 6 : 414
--------------------------------------------------------------------------

sub-19690494
Effective subject number:  7
ses-1
-----------
Eye closed
Raw data shape  (60021, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60021
    Range : 0 ... 60020 =      0.000 ...   120.040 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 15.1s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 2 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0, 16]
fs=200Hz: resampled shape=(24008, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12004, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6002, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (60015, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60015
    Range : 0 ... 60014 =      0.000 ...   120.028 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 11.2s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 2 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0, 25]
fs=200Hz: resampled shape=(24006, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12003, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6001, 26)
fs=50Hz: segments=29
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60024, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60024
    Range : 0 ... 60023 =      0.000 ...   120.046 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 2.1s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 4 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [1, 8, 13, 24]
fs=200Hz: resampled shape=(24009, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12004, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6002, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (60024, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60024
    Range : 0 ... 60023 =      0.000 ...   120.046 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 2.3s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 2 ICA components
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0, 4]
fs=200Hz: resampled shape=(24009, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12004, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6002, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Total segments for Session 7 : 828
--------------------------------------------------------------------------

sub-19690969
Effective subject number:  8
ses-1
-----------
Eye closed
Raw data shape  (60008, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60008
    Range : 0 ... 60007 =      0.000 ...   120.014 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 1.3s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 1 ICA component
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [2]
fs=200Hz: resampled shape=(24003, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12001, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6000, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (59960, 26)
Creating RawArray with float64 data, n_channels=26, n_times=59960
    Range : 0 ... 59959 =      0.000 ...   119.918 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 0.7s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 1 ICA component
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0]
fs=200Hz: resampled shape=(23984, 26)
fs=200Hz: segments=118
fs=100Hz: resampled shape=(11992, 26)
fs=100Hz: segments=58
fs=50Hz: resampled shape=(5996, 26)
fs=50Hz: segments=28
------------End of Task-------------------
ses-2
-----------
Eye closed
Raw data shape  (60024, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60024
    Range : 0 ... 60023 =      0.000 ...   120.046 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 0.9s.
✔ ICA fitted.
No ICs exceeded artifact thresholds. No components excluded.
fs=200Hz: resampled shape=(24009, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12004, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6002, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Eye open
Raw data shape  (60024, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60024
    Range : 0 ... 60023 =      0.000 ...   120.046 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components
Fitting ICA took 0.6s.
✔ ICA fitted.
Applying ICA to Raw instance
    Transforming to ICA space (26 components)
    Zeroing out 1 ICA component
    Projecting back using 26 PCA components
✔ ICA applied. Excluded components: [0]
fs=200Hz: resampled shape=(24009, 26)
fs=200Hz: segments=119
fs=100Hz: resampled shape=(12004, 26)
fs=100Hz: segments=59
fs=50Hz: resampled shape=(6002, 26)
fs=50Hz: segments=29
------------End of Task-------------------
Total segments for Session 8 : 825
--------------------------------------------------------------------------

sub-19691048
Effective subject number:  9
ses-1
-----------
Eye closed
Raw data shape  (60015, 26)
Creating RawArray with float64 data, n_channels=26, n_times=60015
    Range : 0 ... 60014 =      0.000 ...   120.028 secs
Ready.
✔ Montage set: 'standard_1020'.
✔ Notch @ 50 Hz
✔ Bandpass filter applied (0.5–45.0 Hz).
Fitting ICA to data using 26 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 26 components

## Create JSON file

In [18]:
meta = {
    "N": int(N_total),
    "T": SEG_LEN,
    "C": int(n_channels),
    "SAMPLE_RATE_LIST": SAMPLE_RATE_LIST,
    "MONTAGE": "standard_1020",
    "CHANNELS": standard_channels,
    "LABELS": {
        "disease_id": {0: "Healthy Control (HC)"},  # too much others, ignore
        "subject_id": "integer from 1 to number of subjects",
        "sampling_frequency": "integer in SAMPLE_RATE_LIST"
    }
}
with open(meta_path, "w") as f:
    json.dump(meta, f, indent=2)

print("Saved meta:", meta_path)

Saved meta: Processed\L400\TDBrain\meta.json

## Load and check the processed data

In [19]:
# load meta information
meta_path = meta_path  # if you already have meta_path in current notebook
with open(meta_path, "r") as f:
    meta = json.load(f)

N = meta["N"]
T = meta["T"]          # SEG_LEN
C = meta["C"]

print("Meta:")
for k, v in meta.items():
    print(f"{k}: {v}")
print("-------------------------------------")

# open memmap
X_mm = np.memmap(X_path, dtype='float32', mode='r', shape=(N, T, C))
y_mm = np.memmap(y_path, dtype='float32', mode='r', shape=(N, 3))

# subject_id is stored in y[:, 1]
subject_ids = np.unique(y_mm[:, 1]).astype(int)

total_samples = 0
for sid in sorted(subject_ids):
    # find all indices for this subject
    idx = np.where(y_mm[:, 1] == sid)[0]

    # compute shapes logically (do not load all X into memory)
    n_seg = len(idx)
    x_shape = (n_seg, T, C)    # logical X shape for this subject
    y_shape = (n_seg, 3)       # logical y shape for this subject
    total_samples += n_seg
    
    print(f"Subject ID {sid:03d}: X shape={x_shape}, y shape={y_shape}")

print("\nTotal subjects:", len(subject_ids))
print("Total samples:", total_samples)
# option: delete memmap views
del X_mm, y_mm

Meta:
N: 555455
T: 400
C: 26
SAMPLE_RATE_LIST: [200, 100, 50]
MONTAGE: standard_1020
CHANNELS: ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FC3', 'FCz', 'FC4', 'T7', 'C3', 'Cz', 'C4', 'T8', 'CP3', 'CPz', 'CP4', 'P7', 'P3', 'Pz', 'P4', 'P8', 'O1', 'Oz', 'O2']
LABELS: {'disease_id': {'0': 'Healthy Control (HC)'}, 'subject_id': 'integer from 1 to number of subjects', 'sampling_frequency': 'integer in SAMPLE_RATE_LIST'}
-------------------------------------
Subject ID 001: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 002: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 003: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 004: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 005: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 006: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 007: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 008: X shape=(825, 400, 26), y shape=(825, 3)
Subject ID 009: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 010: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 011: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 012: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 013: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 014: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 015: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 016: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 017: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 018: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 019: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 020: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 021: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 022: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 023: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 024: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 025: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 026: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 027: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 028: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 029: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 030: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 031: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 032: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 033: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 034: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 035: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 036: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 037: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 038: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 039: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 040: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 041: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 042: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 043: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 044: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 045: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 046: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 047: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 048: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 049: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 050: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 051: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 052: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 053: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 054: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 055: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 056: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 057: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 058: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 059: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 060: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 061: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 062: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 063: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 064: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 065: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 066: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 067: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 068: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 069: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 070: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 071: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 072: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 073: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 074: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 075: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 076: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 077: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 078: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 079: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 080: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 081: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 082: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 083: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 084: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 085: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 086: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 087: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 088: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 089: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 090: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 091: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 092: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 093: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 094: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 095: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 096: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 097: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 098: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 099: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 100: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 101: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 102: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 103: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 104: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 105: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 106: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 107: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 108: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 109: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 110: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 111: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 112: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 113: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 114: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 115: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 116: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 117: X shape=(1239, 400, 26), y shape=(1239, 3)
Subject ID 118: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 119: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 120: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 121: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 122: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 123: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 124: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 125: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 126: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 127: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 128: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 129: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 130: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 131: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 132: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 133: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 134: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 135: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 136: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 137: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 138: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 139: X shape=(1242, 400, 26), y shape=(1242, 3)
Subject ID 140: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 141: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 142: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 143: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 144: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 145: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 146: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 147: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 148: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 149: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 150: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 151: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 152: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 153: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 154: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 155: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 156: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 157: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 158: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 159: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 160: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 161: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 162: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 163: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 164: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 165: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 166: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 167: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 168: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 169: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 170: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 171: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 172: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 173: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 174: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 175: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 176: X shape=(1242, 400, 26), y shape=(1242, 3)
Subject ID 177: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 178: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 179: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 180: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 181: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 182: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 183: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 184: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 185: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 186: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 187: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 188: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 189: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 190: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 191: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 192: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 193: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 194: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 195: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 196: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 197: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 198: X shape=(1242, 400, 26), y shape=(1242, 3)
Subject ID 199: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 200: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 201: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 202: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 203: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 204: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 205: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 206: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 207: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 208: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 209: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 210: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 211: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 212: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 213: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 214: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 215: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 216: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 217: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 218: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 219: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 220: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 221: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 222: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 223: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 224: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 225: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 226: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 227: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 228: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 229: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 230: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 231: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 232: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 233: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 234: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 235: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 236: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 237: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 238: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 239: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 240: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 241: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 242: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 243: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 244: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 245: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 246: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 247: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 248: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 249: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 250: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 251: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 252: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 253: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 254: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 255: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 256: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 257: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 258: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 259: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 260: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 261: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 262: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 263: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 264: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 265: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 266: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 267: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 268: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 269: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 270: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 271: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 272: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 273: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 274: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 275: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 276: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 277: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 278: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 279: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 280: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 281: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 282: X shape=(828, 400, 26), y shape=(828, 3)
Subject ID 283: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 284: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 285: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 286: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 287: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 288: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 289: X shape=(408, 400, 26), y shape=(408, 3)
Subject ID 290: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 291: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 292: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 293: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 294: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 295: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 296: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 297: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 298: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 299: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 300: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 301: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 302: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 303: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 304: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 305: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 306: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 307: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 308: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 309: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 310: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 311: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 312: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 313: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 314: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 315: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 316: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 317: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 318: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 319: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 320: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 321: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 322: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 323: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 324: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 325: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 326: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 327: X shape=(418, 400, 26), y shape=(418, 3)
Subject ID 328: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 329: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 330: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 331: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 332: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 333: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 334: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 335: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 336: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 337: X shape=(411, 400, 26), y shape=(411, 3)
Subject ID 338: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 339: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 340: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 341: X shape=(414, 400, 26), y shape=(414, 3)
Subject ID 342: X shape=(414, 400, 26), y shape=(414, 3)